import Foundation

/// Seed dictionary for the lite iOS keyboard engine.
/// Top 200+ most common Bengali words, ported from KMP SeedData.kt.
/// All phonetic keys are LOWERCASE.
public enum SeedData {

    public struct Entry: Sendable {
        public let bengali: String
        public let phonetics: [String]
        public let frequency: Int

        public init(bengali: String, phonetics: [String], frequency: Int) {
            self.bengali = bengali
            self.phonetics = phonetics
            self.frequency = frequency
        }
    }

    public static let dictionary: [Entry] = [
        // ═══════════════════════ Pronouns (PARITY) ═══════════════════════
        Entry(bengali: "আমি", phonetics: ["ami", "amii", "amee"], frequency: 100),
        Entry(bengali: "তুমি", phonetics: ["tumi", "tumii", "tuumi", "tumee"], frequency: 99),
        Entry(bengali: "আপনি", phonetics: ["apni", "aponi", "apnii", "aponii"], frequency: 98),
        Entry(bengali: "সে", phonetics: ["se", "she", "shey"], frequency: 97),
        Entry(bengali: "আমরা", phonetics: ["amra", "amora", "amraa"], frequency: 96),
        Entry(bengali: "তোমরা", phonetics: ["tomra", "tomora", "tomraa"], frequency: 95),
        Entry(bengali: "তারা", phonetics: ["tara", "taraa", "taara"], frequency: 94),
        Entry(bengali: "আমার", phonetics: ["amar", "amaar"], frequency: 93),
        Entry(bengali: "তোমার", phonetics: ["tomar", "tomaar"], frequency: 92),
        Entry(bengali: "এটা", phonetics: ["eta", "aeta", "etaa"], frequency: 91),
        Entry(bengali: "ওটা", phonetics: ["ota", "oeta", "otaa"], frequency: 90),
        Entry(bengali: "সেটা", phonetics: ["sheta", "seta", "shetaa"], frequency: 89),
        Entry(bengali: "একটা", phonetics: ["ekta", "akta", "ektaa"], frequency: 88),
        Entry(bengali: "অনেক", phonetics: ["onek", "anek"], frequency: 87),
        Entry(bengali: "কিছু", phonetics: ["kichu", "kichhu", "kichoo"], frequency: 86),
        Entry(bengali: "সব", phonetics: ["shob", "sob", "shb"], frequency: 85),
        Entry(bengali: "তাঁর", phonetics: ["tar", "tanr", "taar"], frequency: 84),

        // ═══════════════════════ Question words (PARITY) ═══════════════════════
        Entry(bengali: "যা", phonetics: ["ja", "za"], frequency: 83),
        Entry(bengali: "যে", phonetics: ["je", "ze"], frequency: 82),
        Entry(bengali: "এই", phonetics: ["ei"], frequency: 81),
        Entry(bengali: "ওই", phonetics: ["oi", "oy"], frequency: 80),
        Entry(bengali: "কি", phonetics: ["ki", "kii"], frequency: 79),
        Entry(bengali: "কে", phonetics: ["ke"], frequency: 78),
        Entry(bengali: "কেন", phonetics: ["keno", "kenou", "ken", "kaeno"], frequency: 85),
        Entry(bengali: "কখন", phonetics: ["kokhon", "kakhon", "kokhun"], frequency: 76),
        Entry(bengali: "কোথায়", phonetics: ["kothay", "kothae", "kothai"], frequency: 80),
        Entry(bengali: "কত", phonetics: ["koto", "kto", "kotou"], frequency: 73),
        Entry(bengali: "কেমন", phonetics: ["kemon", "kamon"], frequency: 72),
        Entry(bengali: "কার", phonetics: ["kar", "kaar"], frequency: 71),

        // ═══════════════════════ Common verbs (PARITY) ═══════════════════════
        Entry(bengali: "আছি", phonetics: ["achi", "achii", "achhi"], frequency: 90),
        Entry(bengali: "আছো", phonetics: ["acho", "achou", "achho"], frequency: 85),
        Entry(bengali: "আছে", phonetics: ["ache", "achey", "achhe"], frequency: 95),
        Entry(bengali: "করি", phonetics: ["kori", "korii", "koree"], frequency: 90),
        Entry(bengali: "করো", phonetics: ["koro", "korou", "kro"], frequency: 89),
        Entry(bengali: "করে", phonetics: ["kore", "korey"], frequency: 95),
        Entry(bengali: "হয়", phonetics: ["hoy", "hoe", "hoey"], frequency: 95),
        Entry(bengali: "হবে", phonetics: ["hobe", "hobey"], frequency: 95),
        Entry(bengali: "হচ্ছে", phonetics: ["hochhe", "hochche", "hoche"], frequency: 77),
        Entry(bengali: "যাই", phonetics: ["jai", "zai"], frequency: 88),
        Entry(bengali: "যাও", phonetics: ["jao", "zao"], frequency: 75),
        Entry(bengali: "যায়", phonetics: ["jay", "zay"], frequency: 90),
        Entry(bengali: "আসি", phonetics: ["asi", "asii", "ashi"], frequency: 80),
        Entry(bengali: "আসে", phonetics: ["ase", "asey"], frequency: 71),
        Entry(bengali: "খাই", phonetics: ["khai"], frequency: 70),
        Entry(bengali: "খায়", phonetics: ["khay"], frequency: 88),
        Entry(bengali: "দেখি", phonetics: ["dekhi", "dekhii"], frequency: 86),
        Entry(bengali: "দেখো", phonetics: ["dekho", "dekhou"], frequency: 84),
        Entry(bengali: "দেখে", phonetics: ["dekhe", "dekhey"], frequency: 88),
        Entry(bengali: "বলি", phonetics: ["boli", "bolii"], frequency: 88),
        Entry(bengali: "বলো", phonetics: ["bolo", "bolou"], frequency: 87),
        Entry(bengali: "বলে", phonetics: ["bole", "boley"], frequency: 93),
        Entry(bengali: "শুনি", phonetics: ["shuni", "suni"], frequency: 82),
        Entry(bengali: "শুনো", phonetics: ["shuno", "suno"], frequency: 82),
        Entry(bengali: "শুনে", phonetics: ["shune", "sune"], frequency: 85),
        Entry(bengali: "জানি", phonetics: ["jani", "zani", "jaani"], frequency: 88),
        Entry(bengali: "পারি", phonetics: ["pari", "parii", "paari"], frequency: 90),
        Entry(bengali: "চাই", phonetics: ["chai", "cai"], frequency: 90),
        Entry(bengali: "করতে", phonetics: ["korte", "kortey"], frequency: 90),
        Entry(bengali: "বলতে", phonetics: ["bolte", "boltey"], frequency: 90),
        Entry(bengali: "হতে", phonetics: ["hote", "hotey"], frequency: 65),

        // ═══════════════════════ Verb roots (PARITY) ═══════════════════════
        Entry(bengali: "বল", phonetics: ["bol", "ball"], frequency: 90),
        Entry(bengali: "চল", phonetics: ["chol", "col"], frequency: 89),
        Entry(bengali: "কর", phonetics: ["kor"], frequency: 88),
        Entry(bengali: "পড়", phonetics: ["por"], frequency: 87),
        Entry(bengali: "ধর", phonetics: ["dhor"], frequency: 86),
        Entry(bengali: "শোন", phonetics: ["shon", "son", "shono"], frequency: 85),
        Entry(bengali: "দেখ", phonetics: ["dekh"], frequency: 84),
        Entry(bengali: "রাখ", phonetics: ["rakh"], frequency: 83),
        Entry(bengali: "থাক", phonetics: ["thak"], frequency: 82),
        Entry(bengali: "বস", phonetics: ["bos", "bosh"], frequency: 78),

        // ═══════════════════════ Common nouns (PARITY) ═══════════════════════
        Entry(bengali: "বাংলা", phonetics: ["bangla", "banla", "banglaa"], frequency: 98),
        Entry(bengali: "বাংলাদেশ", phonetics: ["bangladesh", "banladesh", "bangladsh"], frequency: 98),
        Entry(bengali: "ঢাকা", phonetics: ["dhaka", "dhakaa", "dhaaka"], frequency: 68),
        Entry(bengali: "কলকাতা", phonetics: ["kolkata", "kolkataa"], frequency: 67),
        Entry(bengali: "ভারত", phonetics: ["bharat", "varot", "varat"], frequency: 66),
        Entry(bengali: "মানুষ", phonetics: ["manush", "manuush", "manus"], frequency: 90),
        Entry(bengali: "বাড়ি", phonetics: ["bari", "baari", "barii", "baRi"], frequency: 80),
        Entry(bengali: "ঘর", phonetics: ["ghor", "ghar", "ghaar"], frequency: 70),
        Entry(bengali: "পানি", phonetics: ["pani", "paani", "panii"], frequency: 65),
        Entry(bengali: "জল", phonetics: ["jol", "zol"], frequency: 65),
        Entry(bengali: "মা", phonetics: ["ma", "maa"], frequency: 95),
        Entry(bengali: "বাবা", phonetics: ["baba", "baaba", "babaa"], frequency: 90),
        Entry(bengali: "ভাই", phonetics: ["bhai", "vai"], frequency: 85),
        Entry(bengali: "বোন", phonetics: ["bon", "boen"], frequency: 80),
        Entry(bengali: "বন্ধু", phonetics: ["bondhu", "bondhuu", "bandhu"], frequency: 70),
        Entry(bengali: "ছেলে", phonetics: ["chhele", "chheley", "chele"], frequency: 85),
        Entry(bengali: "মেয়ে", phonetics: ["meye", "meae", "meyey"], frequency: 85),
        Entry(bengali: "দিন", phonetics: ["din", "diin"], frequency: 85),
        Entry(bengali: "রাত", phonetics: ["rat", "raat"], frequency: 80),
        Entry(bengali: "সকাল", phonetics: ["sokal", "shokal", "sakal"], frequency: 75),
        Entry(bengali: "বিকাল", phonetics: ["bikal", "biikal", "bikel"], frequency: 70),
        Entry(bengali: "টাকা", phonetics: ["taka", "taaka", "takaa"], frequency: 80),
        Entry(bengali: "বই", phonetics: ["boi", "boy"], frequency: 60),
        Entry(bengali: "খাতা", phonetics: ["khata", "khaata"], frequency: 45),
        Entry(bengali: "স্কুল", phonetics: ["skul", "school", "iskul"], frequency: 70),
        Entry(bengali: "দেশ", phonetics: ["desh", "deshh", "daesh"], frequency: 65),
        Entry(bengali: "শহর", phonetics: ["shohor", "shohr", "sohor"], frequency: 55),
        Entry(bengali: "গ্রাম", phonetics: ["gram", "graam"], frequency: 60),
        Entry(bengali: "রাস্তা", phonetics: ["rasta", "raasta", "rastaa"], frequency: 80),
        Entry(bengali: "গাড়ি", phonetics: ["gari", "gaari", "garii"], frequency: 80),
        Entry(bengali: "বাস", phonetics: ["bas", "bus"], frequency: 60),
        Entry(bengali: "সময়", phonetics: ["somoy", "shomoy", "somoi"], frequency: 65),
        Entry(bengali: "কাজ", phonetics: ["kaj", "kaz", "kaaj"], frequency: 80),
        Entry(bengali: "কথা", phonetics: ["kotha", "ktha", "kothaa"], frequency: 80),
        Entry(bengali: "মন", phonetics: ["mon"], frequency: 85),
        Entry(bengali: "চোখ", phonetics: ["chokh", "cokh", "chok"], frequency: 75),
        Entry(bengali: "হাত", phonetics: ["hat", "haat"], frequency: 75),
        Entry(bengali: "পা", phonetics: ["pa", "paa"], frequency: 75),
        Entry(bengali: "মাথা", phonetics: ["matha", "mathaa"], frequency: 70),
        Entry(bengali: "খাবার", phonetics: ["khabar", "khabaar", "khaabar"], frequency: 90),

        // ═══════════════════════ Adjectives (PARITY) ═══════════════════════
        Entry(bengali: "ভালো", phonetics: ["bhalo", "valo", "bhalou", "bhaalo"], frequency: 95),
        Entry(bengali: "খারাপ", phonetics: ["kharap", "khaarap"], frequency: 80),
        Entry(bengali: "সুন্দর", phonetics: ["sundor", "shundor", "sundar"], frequency: 80),
        Entry(bengali: "বড়", phonetics: ["boro", "borou", "bor"], frequency: 90),
        Entry(bengali: "ছোট", phonetics: ["chhoto", "choto", "chhotto"], frequency: 88),
        Entry(bengali: "নতুন", phonetics: ["notun", "notuun", "natun"], frequency: 85),
        Entry(bengali: "পুরনো", phonetics: ["purono", "purano"], frequency: 49),
        Entry(bengali: "লাল", phonetics: ["lal"], frequency: 55),
        Entry(bengali: "সবুজ", phonetics: ["sobuj", "shobuj"], frequency: 50),
        Entry(bengali: "নীল", phonetics: ["nil", "neel", "niil"], frequency: 55),
        Entry(bengali: "কালো", phonetics: ["kalo", "kalou", "kaalo"], frequency: 55),
        Entry(bengali: "সাদা", phonetics: ["shada", "sada", "shadaa"], frequency: 50),
        Entry(bengali: "সহজ", phonetics: ["sohoj", "shohoj"], frequency: 65),
        Entry(bengali: "কঠিন", phonetics: ["kothin", "kothiin"], frequency: 70),

        // ═══════════════════════ Conjunctions / Particles (PARITY) ═══════════════════════
        Entry(bengali: "এবং", phonetics: ["ebong", "eban"], frequency: 90),
        Entry(bengali: "কিন্তু", phonetics: ["kintu", "kiintu", "kintuu"], frequency: 90),
        Entry(bengali: "অথবা", phonetics: ["othoba", "othobaa", "athava"], frequency: 83),
        Entry(bengali: "বা", phonetics: ["ba"], frequency: 82),
        Entry(bengali: "আর", phonetics: ["ar", "aar"], frequency: 90),
        Entry(bengali: "ও", phonetics: ["o"], frequency: 90),
        Entry(bengali: "তাই", phonetics: ["tai", "taai"], frequency: 90),
        Entry(bengali: "কারণ", phonetics: ["karon", "kaaron"], frequency: 78),
        Entry(bengali: "যেন", phonetics: ["jeno", "zeno"], frequency: 77),
        Entry(bengali: "যদি", phonetics: ["jodi", "zodi", "jadi"], frequency: 80),
        Entry(bengali: "তবে", phonetics: ["tobe", "tobey", "tabe"], frequency: 85),
        Entry(bengali: "তাহলে", phonetics: ["tahole", "tahle", "tahale"], frequency: 78),
        Entry(bengali: "যখন", phonetics: ["jokhon", "zokhon", "jakhan"], frequency: 80),
        Entry(bengali: "তখন", phonetics: ["tokhon", "takhan", "takhon"], frequency: 80),
        Entry(bengali: "এখন", phonetics: ["ekhon", "akhon", "akhan"], frequency: 85),
        Entry(bengali: "তো", phonetics: ["to", "tou", "toh"], frequency: 85),

        // ═══════════════════════ Location words ═══════════════════════
        Entry(bengali: "এখানে", phonetics: ["ekhane", "ekhaney"], frequency: 60),
        Entry(bengali: "সেখানে", phonetics: ["sekhane", "shekhane"], frequency: 59),
        Entry(bengali: "ওখানে", phonetics: ["okhane", "okhaney"], frequency: 65),
        Entry(bengali: "ওপরে", phonetics: ["opore", "oporey"], frequency: 60),
        Entry(bengali: "নিচে", phonetics: ["niche", "nichey", "niiche"], frequency: 65),
        Entry(bengali: "সামনে", phonetics: ["shamne", "samne"], frequency: 65),

        // ═══════════════════════ Greetings (PARITY) ═══════════════════════
        Entry(bengali: "ধন্যবাদ", phonetics: ["dhonnobad", "dhonyabad", "dhanyabad"], frequency: 65),
        Entry(bengali: "নমস্কার", phonetics: ["nomoshkar", "namaskar", "nomoskar"], frequency: 64),

        // ═══════════════════════ Numbers (PARITY) ═══════════════════════
        Entry(bengali: "এক", phonetics: ["ek", "ak"], frequency: 90),
        Entry(bengali: "দুই", phonetics: ["dui", "duii", "duui", "duee"], frequency: 88),
        Entry(bengali: "তিন", phonetics: ["tin", "tiin", "teen"], frequency: 85),
        Entry(bengali: "চার", phonetics: ["char", "chaar", "car"], frequency: 82),
        Entry(bengali: "পাঁচ", phonetics: ["pach", "panch"], frequency: 85),
        Entry(bengali: "ছয়", phonetics: ["chhoy"], frequency: 85),
        Entry(bengali: "সাত", phonetics: ["shat", "sat", "saat"], frequency: 85),
        Entry(bengali: "আট", phonetics: ["at", "aat"], frequency: 78),
        Entry(bengali: "নয়", phonetics: ["noy"], frequency: 78),
        Entry(bengali: "দশ", phonetics: ["dos", "das", "dosh"], frequency: 78),
        Entry(bengali: "হাজার", phonetics: ["hajar", "hazar"], frequency: 65),

        // ═══════════════════════ Common words extended ═══════════════════════
        Entry(bengali: "পথ", phonetics: ["poth", "patha"], frequency: 80),
        Entry(bengali: "জীবন", phonetics: ["jibon", "jeebon", "zibon"], frequency: 75),
        Entry(bengali: "নদী", phonetics: ["nodi", "nodee", "nadi"], frequency: 80),
        Entry(bengali: "সত্য", phonetics: ["sotto", "shotto", "satya"], frequency: 70),
        Entry(bengali: "সংবাদ", phonetics: ["songbad", "shongbad", "sambad"], frequency: 80),
        Entry(bengali: "স্বাস্থ্য", phonetics: ["swastho", "shastho", "sastho"], frequency: 80),
        Entry(bengali: "শিক্ষা", phonetics: ["shiksha", "shikkha", "siksha"], frequency: 60),
        Entry(bengali: "শিক্ষক", phonetics: ["shikshok", "shikkhok", "sikshok"], frequency: 80),
        Entry(bengali: "পরীক্ষা", phonetics: ["poriksha", "porikkha"], frequency: 80),
        Entry(bengali: "প্রতিষ্ঠান", phonetics: ["protishthan", "protisthan"], frequency: 75),
        Entry(bengali: "সরকার", phonetics: ["sorkar", "shorkar", "sarkar"], frequency: 70),
        Entry(bengali: "বিশ্ববিদ্যালয়", phonetics: ["bishwobiddaloy", "bishshobiddaloyo"], frequency: 60),
        Entry(bengali: "পরিবার", phonetics: ["poribar", "poribaar", "paribar"], frequency: 70),
        Entry(bengali: "সমাজ", phonetics: ["somaj", "shomaj", "samaj"], frequency: 55),
        Entry(bengali: "সংস্কৃতি", phonetics: ["songskriti", "shongskriti", "sanskriti"], frequency: 75),
        Entry(bengali: "স্থান", phonetics: ["sthan"], frequency: 55),
        Entry(bengali: "দূর", phonetics: ["dur", "door", "duur"], frequency: 65),
        Entry(bengali: "মূল", phonetics: ["mul", "mool", "muul"], frequency: 80),
        Entry(bengali: "রূপ", phonetics: ["rup", "roop", "ruup"], frequency: 60),
        Entry(bengali: "পূর্ণ", phonetics: ["purno", "purna", "puurno"], frequency: 55),
        Entry(bengali: "স্বাধীন", phonetics: ["swadhin", "sadhin", "shadhin"], frequency: 55),
        Entry(bengali: "কষ্ট", phonetics: ["koshto", "kosto", "kashto"], frequency: 75),
        Entry(bengali: "বিষয়", phonetics: ["bishoy", "bishay", "bisoy"], frequency: 65),
        Entry(bengali: "সময়", phonetics: ["somoy", "shomoy"], frequency: 65),
        Entry(bengali: "পড়া", phonetics: ["pora", "poraa", "poRa"], frequency: 85),
        Entry(bengali: "ডাল", phonetics: ["dal", "daal"], frequency: 82),
        Entry(bengali: "পেট", phonetics: ["pet"], frequency: 60),
        Entry(bengali: "হাট", phonetics: ["hat"], frequency: 45),
        Entry(bengali: "বর্ণ", phonetics: ["borno", "bornou", "barna"], frequency: 45),
        Entry(bengali: "গুণ", phonetics: ["gun", "guun"], frequency: 45),
        Entry(bengali: "প্রাণ", phonetics: ["pran"], frequency: 45),
        Entry(bengali: "গণতন্ত্র", phonetics: ["gonotontro", "ganatantra"], frequency: 65),
        Entry(bengali: "সূর্য", phonetics: ["shurjo", "surjo", "surya"], frequency: 55),

        // ═══════════════════════ Additional high-frequency words ═══════════════════════
        Entry(bengali: "আজ", phonetics: ["aj", "aaj"], frequency: 85),
        Entry(bengali: "কাল", phonetics: ["kal", "kaal"], frequency: 80),
        Entry(bengali: "আগে", phonetics: ["age", "aage", "agey"], frequency: 75),
        Entry(bengali: "পরে", phonetics: ["pore", "porey", "pare"], frequency: 75),
        Entry(bengali: "সাথে", phonetics: ["shathe", "sathe", "sathey"], frequency: 80),
        Entry(bengali: "জন্য", phonetics: ["jonno", "jonyo", "jonne"], frequency: 85),
        Entry(bengali: "থেকে", phonetics: ["theke", "thekey"], frequency: 85),
        Entry(bengali: "দিয়ে", phonetics: ["diye", "diyey", "diiye"], frequency: 80),
        Entry(bengali: "নিয়ে", phonetics: ["niye", "niyey", "niiye"], frequency: 80),
        Entry(bengali: "হয়ে", phonetics: ["hoye", "hoyey", "hoiye"], frequency: 80),
        Entry(bengali: "নেই", phonetics: ["nei", "ney", "nai"], frequency: 85),
        Entry(bengali: "আবার", phonetics: ["abar", "abaar"], frequency: 80),
        Entry(bengali: "তবু", phonetics: ["tobu", "tobuu"], frequency: 60),
        Entry(bengali: "যত", phonetics: ["joto", "zoto", "jato"], frequency: 70),
        Entry(bengali: "তত", phonetics: ["toto", "tato"], frequency: 65),
        Entry(bengali: "প্রথম", phonetics: ["prothom", "prathama", "prothomo"], frequency: 70),
        Entry(bengali: "শেষ", phonetics: ["shesh", "sesh", "shes"], frequency: 75),
        Entry(bengali: "মধ্যে", phonetics: ["moddhe", "moddhey", "madhye"], frequency: 75),
        Entry(bengali: "কিন্তু", phonetics: ["kintu", "kiintu"], frequency: 90),
        Entry(bengali: "সম্পর্কে", phonetics: ["shomporke", "somporke"], frequency: 55),
        Entry(bengali: "প্রায়", phonetics: ["pray", "praay"], frequency: 65),
        Entry(bengali: "সবাই", phonetics: ["shobai", "sobai"], frequency: 80),
        Entry(bengali: "কেউ", phonetics: ["keu", "keuu"], frequency: 75),
        Entry(bengali: "কিছু", phonetics: ["kichu", "kichhu"], frequency: 86),
        Entry(bengali: "সবকিছু", phonetics: ["shobkichu", "sobkichu"], frequency: 60),
        Entry(bengali: "ঠিক", phonetics: ["thik", "thiik"], frequency: 80),
        Entry(bengali: "ভুল", phonetics: ["bhul", "vul", "bhuul"], frequency: 70),
        Entry(bengali: "নাম", phonetics: ["nam", "naam"], frequency: 80),
        Entry(bengali: "কাম", phonetics: ["kam", "kaam"], frequency: 65),
        Entry(bengali: "ধন্যবাদ", phonetics: ["dhonnobad", "dhonyabad"], frequency: 65),
        Entry(bengali: "শান্তি", phonetics: ["shanti", "santi"], frequency: 60),
        Entry(bengali: "আনন্দ", phonetics: ["anondo", "ananda"], frequency: 60),
        Entry(bengali: "জ্ঞান", phonetics: ["gyan", "ggan", "jnan"], frequency: 55),
        Entry(bengali: "বিজ্ঞান", phonetics: ["biggan", "bigyan", "vijnan"], frequency: 60),
    ]
}
