#!/usr/bin/env python3
"""S185 — regenerate the English suggestion data in shared/.

  EnglishWordData.kt   : the S96 15K OpenSubtitles list (kept verbatim, its
                         curated contractions stay at their ranks) extended
                         with the next letters-only ranks of
                         dictionary-compiler/data/en_50k.txt that are also CMU
                         dictionary headwords, up to 30,000 words.
  EnglishBigramData.kt : next-word context — Peter Norvig's count_2w.txt
                         (Google Web Trillion Word Corpus bigram counts,
                         https://norvig.com/ngrams/count_2w.txt), restricted to
                         pairs whose both words are in the 30K list, the top
                         followers per previous word.

Usage: python3 scripts/gen_english_data.py /path/to/count_2w.txt
"""
import re, sys, collections
ROOT = __import__('os').path.dirname(__import__('os').path.dirname(__import__('os').path.abspath(__file__)))
WORD_KT = f"{ROOT}/shared/src/commonMain/kotlin/com/banglu/engine/english/EnglishWordData.kt"
BIGRAM_KT = f"{ROOT}/shared/src/commonMain/kotlin/com/banglu/engine/english/EnglishBigramData.kt"
EN50K = f"{ROOT}/dictionary-compiler/data/en_50k.txt"
CMUDICT = f"{ROOT}/dictionary-compiler/data/cmudict.dict"   # real-word filter for the appended ranks
TARGET_WORDS = 30000
MAX_PREV_RANK = 12000
FOLLOWERS = 5
MIN_PAIR_COUNT = 20000
# Words never offered unprompted as a next-word prediction (they stay typeable
# and completable — this list only gates the context chips).
BLOCK = set("fuck fucking fucked fucker fuckers shit shitty bitch bitches ass asshole assholes dick dicks pussy pussies cock cocks cunt cunts whore whores slut sluts nigger niggers fag faggot faggots".split())

def chunks(words, limit=60000):
    out, cur, size = [], [], 0
    for w in words:
        if size + len(w.encode()) + 1 > limit:
            out.append(" ".join(cur)); cur, size = [], 0
        cur.append(w); size += len(w.encode()) + 1
    if cur: out.append(" ".join(cur))
    return out

def write_kt(path, obj, doc, consts, expr):
    body = "\n\n".join(f'    private const val C{i} = "{c}"' for i, c in enumerate(consts))
    open(path, "w").write(f"""package com.banglu.engine.english

{doc}
internal object {obj} {{
{body}

    {expr}
}}
""")

# ── words ──
# The S96 base list is the committed 15,026-word file (git v1.5.118); a
# regenerated file must never feed itself, or the appended ranks would be
# treated as the curated base.
import subprocess
src = subprocess.run(["git", "-C", ROOT, "show", "v1.5.118:shared/src/commonMain/kotlin/com/banglu/engine/english/EnglishWordData.kt"], capture_output=True, text=True, check=True).stdout
existing = " ".join(re.findall(r'private const val C\d+ = "([^"]*)"', src)).split()
assert len(existing) == 15026, len(existing)
seen = set(existing)
words = list(existing)
# The subtitle list carries typos (helo, doesnt) past the top ranks; an
# appended word must also be a CMU dictionary headword.
cmu = set()
for line in open(CMUDICT, encoding="utf-8", errors="ignore"):
    h = line.split(" ", 1)[0]
    cmu.add(re.sub(r"\(\d+\)$", "", h))
for line in open(EN50K):
    w = line.split()[0]
    if len(words) >= TARGET_WORDS: break
    if w in seen or not re.fullmatch(r"[a-z]+", w) or w not in cmu: continue
    if len(w) == 1 and w not in ("a", "i"): continue
    words.append(w); seen.add(w)
wc = chunks(words)
write_kt(WORD_KT, "EnglishWordData", f"""/**
 * S96/S185: English suggestion wordlist — top tokens of the OpenSubtitles 2018
 * English frequency list (dictionary-compiler/data/en_50k.txt, licensed in
 * LICENSES.md), letters-only, FREQUENCY ORDER (index = rank), plus curated
 * contractions inserted at their base word's rank (S96). S185 extended the
 * list from 15,026 to {len(words)} words so inflections (receiving, stopped) and
 * longer words complete. GENERATED by scripts/gen_english_data.py — do not
 * hand-edit.
 *
 * Stored as chunked string constants: a 30K-element arrayOf() literal
 * exceeds JVM method/constant limits and crashed the compiler daemon.
 */""", wc, "val WORDS: List<String> by lazy { (" + " + \" \" + ".join(f"C{i}" for i in range(len(wc))) + ").split(' ') }")
rank = {w: i for i, w in enumerate(words)}

# ── bigrams ──
counts = collections.Counter()   # case variants of the same pair are merged
for line in open(sys.argv[1], encoding="utf-8", errors="ignore"):
    try:
        pair, cnt = line.rstrip("\n").split("\t"); a, b = pair.lower().split(" "); cnt = int(cnt)
    except ValueError: continue
    if a == b or a not in rank or b not in rank: continue
    if rank[a] >= MAX_PREV_RANK or b in BLOCK: continue
    if len(b) == 1 and b not in ("a", "i"): continue
    counts[(a, b)] += cnt
foll = collections.defaultdict(list)
for (a, b), cnt in counts.items():
    if cnt >= MIN_PAIR_COUNT: foll[a].append((cnt, b))
entries = []
for a in sorted(foll, key=lambda k: rank[k]):
    top = [b for _, b in sorted(foll[a], reverse=True)[:FOLLOWERS]]
    entries.append(a + ":" + ",".join(top))
bc = chunks(entries)
write_kt(BIGRAM_KT, "EnglishBigramData", f"""/**
 * S185: English next-word context (user: "add context wording in English —
 * when they press spacebar show the next-word suggestion"). Bigram counts from
 * Peter Norvig's count_2w.txt (Google Web Trillion Word Corpus,
 * https://norvig.com/ngrams/count_2w.txt, public research data), restricted to
 * pairs whose both words are in EnglishWordData, previous word within the top
 * {MAX_PREV_RANK} ranks, pair count ≥ {MIN_PAIR_COUNT}, top {FOLLOWERS} followers per previous word:
 * {len(entries)} previous words. Format "prev:next1,next2,…" separated by
 * spaces. GENERATED by scripts/gen_english_data.py — do not hand-edit.
 */""", bc, "val ENTRIES: List<String> by lazy { (" + " + \" \" + ".join(f"C{i}" for i in range(len(bc))) + ").split(' ') }")
print(f"words={len(words)} chunks={len(wc)}  bigram prevs={len(entries)} chunks={len(bc)} bytes={sum(len(c) for c in bc)}")
