package com.banglu.keyboard

/**
 * S57: per-emoji search keywords — English names + Bangla + Banglish — so the
 * emoji search understands all three scripts (hasi, হাসি, laugh all hit 😂).
 * Compiled into the APK; fully offline.
 */
object EmojiKeywords {

    val keywords: Map<String, List<String>> = mapOf(
        // ── Smileys ────────────────────────────────────────────────────────
        "😀" to listOf("grin", "smile", "happy", "hasi", "হাসি", "খুশি", "khushi"),
        "😃" to listOf("smile", "happy", "joy", "hasi", "হাসি"),
        "😄" to listOf("smile", "laugh", "happy", "hasi", "হাসি"),
        "😁" to listOf("grin", "beam", "hasi", "হাসি", "দাঁত"),
        "😆" to listOf("laugh", "haha", "hasi", "হাসি", "মজা"),
        "😅" to listOf("sweat", "relief", "haha", "hasi", "হাসি"),
        "🤣" to listOf("rofl", "rolling", "laugh", "haha", "hasi", "হাসি", "মজা"),
        "😂" to listOf("joy", "laugh", "haha", "lol", "tears", "hasi", "hashi", "হাসি", "মজা"),
        "🙂" to listOf("smile", "slight", "hasi", "হাসি"),
        "🙃" to listOf("upside down", "silly", "ulta", "উল্টা"),
        "😉" to listOf("wink", "chokh mara", "চোখ"),
        "😊" to listOf("blush", "smile", "happy", "lojja", "হাসি", "লজ্জা"),
        "😇" to listOf("angel", "halo", "innocent", "ফেরেশতা", "নিষ্পাপ"),
        "🥰" to listOf("love", "hearts", "adore", "bhalobasha", "valobasha", "ভালোবাসা"),
        "😍" to listOf("heart eyes", "love", "bhalobasha", "ভালোবাসা", "প্রেম"),
        "🤩" to listOf("star struck", "wow", "excited", "অসাধারণ", "তারকা"),
        "😘" to listOf("kiss", "chumu", "চুমু", "adore"),
        "😗" to listOf("kiss", "chumu", "চুমু"),
        "😚" to listOf("kiss", "closed eyes", "chumu", "চুমু"),
        "😙" to listOf("kiss", "smile", "chumu", "চুমু"),
        "🥲" to listOf("happy tear", "grateful", "কান্না", "খুশি"),
        "😋" to listOf("yummy", "tasty", "mojar", "মজা", "খাবার"),
        "😛" to listOf("tongue", "jibh", "জিভ"),
        "😜" to listOf("wink tongue", "crazy", "pagol", "পাগল", "জিভ"),
        "🤪" to listOf("zany", "crazy", "pagol", "পাগল"),
        "😝" to listOf("tongue", "squint", "জিভ"),
        "🤑" to listOf("money", "rich", "taka", "টাকা", "ধনী"),
        "🤗" to listOf("hug", "jorie dhora", "জড়িয়ে", "আলিঙ্গন"),
        "🤭" to listOf("giggle", "oops", "lojja", "লজ্জা"),
        "🤫" to listOf("shush", "quiet", "secret", "chup", "চুপ"),
        "🤔" to listOf("thinking", "hmm", "bhabchi", "ভাবছি", "চিন্তা"),
        "🫡" to listOf("salute", "yes sir", "স্যালুট"),
        "🤐" to listOf("zipper", "quiet", "chup", "চুপ"),
        "🤨" to listOf("eyebrow", "suspicious", "sondeho", "সন্দেহ"),
        "😐" to listOf("neutral", "meh", "চুপচাপ"),
        "😑" to listOf("expressionless", "birokto", "বিরক্ত"),
        "😶" to listOf("no mouth", "speechless", "নির্বাক"),
        "😏" to listOf("smirk", "sly", "dushtu", "দুষ্টু"),
        "😒" to listOf("unamused", "birokto", "বিরক্ত"),
        "🙄" to listOf("eye roll", "birokto", "বিরক্ত", "উফ"),
        "😬" to listOf("grimace", "awkward", "অস্বস্তি"),
        "🤥" to listOf("lie", "pinocchio", "mittha", "মিথ্যা"),
        "😌" to listOf("relieved", "peace", "shanti", "শান্তি"),
        "😔" to listOf("pensive", "sad", "mon kharap", "মন খারাপ", "দুঃখ"),
        "😪" to listOf("sleepy", "ghum", "ঘুম"),
        "🤤" to listOf("drool", "lova", "লোভ"),
        "😴" to listOf("sleep", "zzz", "ghum", "ঘুম", "ঘুমাচ্ছি"),
        "😷" to listOf("mask", "sick", "osukh", "অসুখ", "মাস্ক"),
        "🤒" to listOf("fever", "sick", "jor", "জ্বর", "অসুখ"),
        "🤕" to listOf("injured", "bandage", "byatha", "ব্যথা", "আঘাত"),
        "🤢" to listOf("nausea", "sick", "bomi", "বমি"),
        "🤮" to listOf("vomit", "bomi", "বমি"),
        "🤧" to listOf("sneeze", "hachi", "হাঁচি", "সর্দি"),
        "🥵" to listOf("hot", "gorom", "গরম"),
        "🥶" to listOf("cold", "freezing", "thanda", "ঠান্ডা", "শীত"),
        "🥴" to listOf("woozy", "dizzy", "মাতাল"),
        "😵" to listOf("dizzy", "knocked out", "মাথা ঘোরা"),
        "🤯" to listOf("mind blown", "shocked", "অবাক"),
        "🤠" to listOf("cowboy", "টুপি"),
        "🥳" to listOf("party", "celebrate", "utshob", "উৎসব", "পার্টি"),
        "🥸" to listOf("disguise", "ছদ্মবেশ"),
        "😎" to listOf("cool", "sunglasses", "স্টাইল", "চশমা"),
        "🤓" to listOf("nerd", "study", "porua", "পড়ুয়া", "চশমা"),
        "🧐" to listOf("monocle", "inspect", "খোঁজা"),
        "😕" to listOf("confused", "confusion", "দ্বিধা"),
        "😟" to listOf("worried", "chinta", "চিন্তা"),
        "🙁" to listOf("frown", "sad", "mon kharap", "মন খারাপ"),
        "😮" to listOf("wow", "open mouth", "obak", "অবাক"),
        "😯" to listOf("hushed", "surprised", "obak", "অবাক"),
        "😲" to listOf("astonished", "shocked", "obak", "অবাক"),
        "😳" to listOf("flushed", "blush", "lojja", "লজ্জা", "অবাক"),
        "🥺" to listOf("pleading", "puppy eyes", "please", "অনুরোধ", "মায়া"),
        "🥹" to listOf("holding tears", "touched", "কান্না", "আবেগ"),
        "😦" to listOf("frown", "shocked", "অবাক"),
        "😧" to listOf("anguished", "কষ্ট"),
        "😨" to listOf("fearful", "scared", "bhoy", "ভয়"),
        "😰" to listOf("anxious", "sweat", "chinta", "চিন্তা", "ভয়"),
        "😥" to listOf("sad relieved", "dukkho", "দুঃখ"),
        "😢" to listOf("cry", "tear", "kanna", "কান্না", "দুঃখ"),
        "😭" to listOf("cry", "sob", "kanna", "কান্না", "কাঁদছি"),
        "😱" to listOf("scream", "fear", "bhoy", "ভয়", "চিৎকার"),
        "😖" to listOf("confounded", "কষ্ট"),
        "😣" to listOf("persevere", "কষ্ট"),
        "😞" to listOf("disappointed", "hotash", "হতাশ", "মন খারাপ"),
        "😓" to listOf("sweat", "tired", "klanto", "ক্লান্ত"),
        "😩" to listOf("weary", "tired", "klanto", "ক্লান্ত", "উফ"),
        "😫" to listOf("tired", "klanto", "ক্লান্ত"),
        "🥱" to listOf("yawn", "sleepy", "ghum", "ঘুম", "হাই"),
        "😤" to listOf("frustrated", "huff", "rag", "রাগ"),
        "😡" to listOf("angry", "rage", "rag", "raag", "রাগ", "গোস্সা"),
        "😠" to listOf("angry", "mad", "rag", "রাগ"),
        "🤬" to listOf("cursing", "swear", "rag", "রাগ", "গালি"),
        "😈" to listOf("devil", "dushtu", "দুষ্টু", "শয়তান"),
        "👿" to listOf("angry devil", "শয়তান", "রাগ"),
        "💀" to listOf("skull", "dead", "মৃত", "খুলি"),
        "☠️" to listOf("skull crossbones", "danger", "বিপদ"),
        "💩" to listOf("poop", "funny", "হাগু"),
        "🤡" to listOf("clown", "joker", "জোকার"),
        "👻" to listOf("ghost", "bhoot", "ভূত"),
        "👽" to listOf("alien", "এলিয়েন"),
        "🤖" to listOf("robot", "রোবট"),

        // ── Gestures & body ────────────────────────────────────────────────
        "👋" to listOf("wave", "hi", "bye", "hat", "হাত", "টাটা"),
        "🤚" to listOf("raised hand", "stop", "hat", "হাত"),
        "✋" to listOf("hand", "stop", "high five", "হাত", "থামো"),
        "🖖" to listOf("vulcan", "spock", "হাত"),
        "👌" to listOf("ok", "perfect", "thik ache", "ঠিক আছে", "okay"),
        "🤌" to listOf("pinched fingers", "italian", "কী"),
        "✌️" to listOf("victory", "peace", "জয়", "ভিক্টরি"),
        "🤞" to listOf("crossed fingers", "luck", "dua", "দোয়া", "আশা"),
        "🤟" to listOf("love you", "rock", "ভালোবাসা"),
        "🤘" to listOf("rock", "horns", "রক"),
        "🤙" to listOf("call me", "phone", "ফোন", "কল"),
        "👈" to listOf("point left", "বামে", "আঙুল"),
        "👉" to listOf("point right", "ডানে", "আঙুল"),
        "👆" to listOf("point up", "উপরে", "আঙুল"),
        "👇" to listOf("point down", "নিচে", "আঙুল"),
        "☝️" to listOf("index up", "one", "এক", "আঙুল"),
        "👍" to listOf("thumbs up", "like", "good", "bhalo", "valo", "ভালো", "লাইক"),
        "👎" to listOf("thumbs down", "dislike", "bad", "kharap", "খারাপ"),
        "✊" to listOf("fist", "power", "protibad", "প্রতিবাদ", "ঘুষি"),
        "👊" to listOf("punch", "fist bump", "ঘুষি"),
        "🤛" to listOf("fist left", "ঘুষি"),
        "🤜" to listOf("fist right", "ঘুষি"),
        "👏" to listOf("clap", "applause", "hattali", "হাততালি", "বাহবা"),
        "🙌" to listOf("raise hands", "hooray", "celebration", "উল্লাস"),
        "👐" to listOf("open hands", "হাত"),
        "🤲" to listOf("palms up", "dua", "prayer", "দোয়া", "মোনাজাত"),
        "🤝" to listOf("handshake", "deal", "চুক্তি", "হ্যান্ডশেক"),
        "🙏" to listOf("pray", "thanks", "please", "dua", "dhonnobad", "ধন্যবাদ", "দোয়া", "নমস্কার"),
        "✍️" to listOf("writing", "lekha", "লেখা"),
        "💅" to listOf("nails", "makeup", "নখ", "সাজ"),
        "🤳" to listOf("selfie", "সেলফি"),
        "💪" to listOf("muscle", "strong", "shokti", "শক্তি", "জিম"),
        "👀" to listOf("eyes", "look", "chokh", "চোখ", "দেখা"),
        "👁️" to listOf("eye", "chokh", "চোখ"),
        "👂" to listOf("ear", "listen", "kan", "কান", "শোনা"),
        "👃" to listOf("nose", "nak", "নাক"),
        "🧠" to listOf("brain", "smart", "buddhi", "বুদ্ধি", "মাথা"),
        "🦷" to listOf("tooth", "dat", "দাঁত"),
        "👄" to listOf("lips", "mouth", "thot", "ঠোঁট"),
        "💋" to listOf("kiss mark", "chumu", "চুমু"),

        // ── Hearts & symbols ───────────────────────────────────────────────
        "❤️" to listOf("heart", "love", "red heart", "bhalobasha", "valobasha", "ভালোবাসা", "হার্ট", "প্রেম", "মন"),
        "🧡" to listOf("orange heart", "love", "ভালোবাসা", "হার্ট"),
        "💛" to listOf("yellow heart", "love", "ভালোবাসা", "হার্ট"),
        "💚" to listOf("green heart", "love", "ভালোবাসা", "হার্ট"),
        "💙" to listOf("blue heart", "love", "ভালোবাসা", "হার্ট"),
        "💜" to listOf("purple heart", "love", "ভালোবাসা", "হার্ট"),
        "🖤" to listOf("black heart", "love", "ভালোবাসা", "হার্ট"),
        "🤍" to listOf("white heart", "love", "ভালোবাসা", "হার্ট"),
        "🤎" to listOf("brown heart", "love", "ভালোবাসা", "হার্ট"),
        "💔" to listOf("broken heart", "heartbreak", "mon bhanga", "কষ্ট", "ছ্যাঁকা", "ভাঙা মন"),
        "❤️‍🔥" to listOf("heart fire", "passion", "ভালোবাসা", "আগুন"),
        "❤️‍🩹" to listOf("mending heart", "healing", "ভালোবাসা"),
        "❣️" to listOf("heart exclamation", "ভালোবাসা"),
        "💕" to listOf("two hearts", "love", "ভালোবাসা"),
        "💞" to listOf("revolving hearts", "love", "ভালোবাসা"),
        "💓" to listOf("beating heart", "love", "ভালোবাসা"),
        "💗" to listOf("growing heart", "love", "ভালোবাসা"),
        "💖" to listOf("sparkling heart", "love", "ভালোবাসা"),
        "💘" to listOf("cupid", "arrow heart", "প্রেম"),
        "💝" to listOf("heart gift", "ভালোবাসা", "উপহার"),
        "💯" to listOf("hundred", "perfect", "einsho", "একশো", "সেরা"),
        "✅" to listOf("check", "done", "ok", "thik", "ঠিক", "হয়েছে", "টিক"),
        "❌" to listOf("cross", "no", "wrong", "na", "না", "ভুল", "ক্রস"),
        "⚠️" to listOf("warning", "careful", "sabdhan", "সাবধান", "সতর্ক"),
        "❓" to listOf("question", "proshno", "প্রশ্ন"),
        "❗" to listOf("exclamation", "important", "জরুরি"),
        "🚫" to listOf("prohibited", "no", "nishedh", "নিষেধ"),
        "♻️" to listOf("recycle", "রিসাইকেল"),
        "🆗" to listOf("ok", "okay", "ঠিক আছে"),
        "🔞" to listOf("18", "adult", "প্রাপ্তবয়স্ক"),
        "☪️" to listOf("star crescent", "islam", "ইসলাম", "চাঁদ তারা"),
        "🕌" to listOf("mosque", "masjid", "মসজিদ", "নামাজ"),
        "🕋" to listOf("kaaba", "hajj", "কাবা", "হজ"),
        "📿" to listOf("prayer beads", "tasbih", "তসবিহ"),
        "🛐" to listOf("worship", "prayer", "উপাসনা"),
        "🕉️" to listOf("om", "hindu", "ওম"),
        "✝️" to listOf("cross", "christian", "ক্রস"),

        // ── Celebration & nature ───────────────────────────────────────────
        "🎉" to listOf("party", "celebration", "congrats", "ovinondon", "অভিনন্দন", "উৎসব", "পার্টি"),
        "🎊" to listOf("confetti", "celebration", "উৎসব"),
        "🎂" to listOf("cake", "birthday", "jonmodin", "জন্মদিন", "কেক"),
        "🎁" to listOf("gift", "present", "upohar", "উপহার", "গিফট"),
        "🎈" to listOf("balloon", "party", "বেলুন"),
        "🎆" to listOf("fireworks", "atoshbaji", "আতশবাজি"),
        "🎇" to listOf("sparkler", "আতশবাজি"),
        "✨" to listOf("sparkles", "shine", "ঝলমল", "সুন্দর"),
        "🌟" to listOf("glowing star", "tara", "তারা"),
        "⭐" to listOf("star", "tara", "তারা"),
        "🔥" to listOf("fire", "lit", "darun", "দারুণ", "আগুন", "ফায়ার"),
        "🌙" to listOf("moon", "crescent", "chad", "চাঁদ", "eid", "ঈদ", "রাত"),
        "🌛" to listOf("moon face", "chad", "চাঁদ"),
        "☀️" to listOf("sun", "surjo", "সূর্য", "রোদ", "সকাল"),
        "🌈" to listOf("rainbow", "rongdhonu", "রংধনু"),
        "☁️" to listOf("cloud", "megh", "মেঘ"),
        "🌧️" to listOf("rain", "bristi", "বৃষ্টি"),
        "⛈️" to listOf("storm", "thunder", "jhor", "ঝড়", "বজ্র"),
        "🌩️" to listOf("lightning", "bidyut", "বিদ্যুৎ", "বাজ"),
        "❄️" to listOf("snow", "winter", "thanda", "ঠান্ডা", "শীত", "বরফ"),
        "🌊" to listOf("wave", "sea", "dheu", "ঢেউ", "সমুদ্র"),
        "🌺" to listOf("hibiscus", "flower", "ful", "ফুল", "জবা"),
        "🌸" to listOf("blossom", "flower", "ful", "ফুল"),
        "🌹" to listOf("rose", "flower", "golap", "গোলাপ", "ফুল"),
        "🌻" to listOf("sunflower", "surjomukhi", "সূর্যমুখী", "ফুল"),
        "🌷" to listOf("tulip", "flower", "ফুল"),
        "💐" to listOf("bouquet", "flowers", "ful", "ফুল", "তোড়া"),
        "🌿" to listOf("herb", "leaf", "pata", "পাতা", "সবুজ"),
        "🌳" to listOf("tree", "gach", "গাছ"),
        "🌴" to listOf("palm tree", "narikel gach", "নারিকেল", "গাছ"),

        // ── Animals (common) ───────────────────────────────────────────────
        "🐱" to listOf("cat", "biral", "বিড়াল"),
        "🐶" to listOf("dog", "kukur", "কুকুর"),
        "🐮" to listOf("cow", "goru", "গরু"),
        "🐐" to listOf("goat", "chagol", "ছাগল"),
        "🐔" to listOf("chicken", "murgi", "মুরগি"),
        "🐟" to listOf("fish", "mach", "মাছ"),
        "🐠" to listOf("tropical fish", "mach", "মাছ"),
        "🦆" to listOf("duck", "hash", "হাঁস"),
        "🐘" to listOf("elephant", "hati", "হাতি"),
        "🐅" to listOf("tiger", "bagh", "বাঘ", "রয়েল বেঙ্গল"),
        "🐯" to listOf("tiger face", "bagh", "বাঘ"),
        "🦁" to listOf("lion", "singho", "সিংহ"),
        "🐒" to listOf("monkey", "bandor", "বানর"),
        "🐍" to listOf("snake", "shap", "সাপ"),
        "🐦" to listOf("bird", "pakhi", "পাখি"),
        "🦋" to listOf("butterfly", "projapoti", "প্রজাপতি"),
        "🐝" to listOf("bee", "moumachhi", "মৌমাছি"),
        "🐜" to listOf("ant", "pipra", "পিঁপড়া"),
        "🦟" to listOf("mosquito", "mosha", "মশা"),
        "🐸" to listOf("frog", "bang", "ব্যাঙ"),
        "🐁" to listOf("mouse", "idur", "ইঁদুর"),

        // ── Food (Bangladeshi favourites first) ────────────────────────────
        "🍛" to listOf("curry rice", "biryani", "biriyani", "bhat", "ভাত", "বিরিয়ানি", "তরকারি"),
        "🍚" to listOf("rice", "bhat", "ভাত", "চাল"),
        "🍜" to listOf("noodles", "ramen", "নুডলস"),
        "🍲" to listOf("stew", "curry", "tarkari", "তরকারি", "ঝোল"),
        "🥘" to listOf("paella", "curry", "খিচুড়ি", "রান্না"),
        "🍗" to listOf("chicken leg", "murgi", "মুরগি", "মাংস"),
        "🍖" to listOf("meat", "mangsho", "মাংস", "গোশত"),
        "🍤" to listOf("shrimp", "chingri", "চিংড়ি"),
        "🥚" to listOf("egg", "dim", "ডিম"),
        "🍳" to listOf("fried egg", "dim bhaja", "ডিম", "রান্না"),
        "🧆" to listOf("falafel", "chop", "চপ", "বড়া"),
        "🥟" to listOf("dumpling", "puli", "পুলি", "মোমো"),
        "🍞" to listOf("bread", "ruti", "রুটি", "পাউরুটি"),
        "🫓" to listOf("flatbread", "ruti", "porota", "রুটি", "পরোটা"),
        "🍕" to listOf("pizza", "পিৎজা"),
        "🍔" to listOf("burger", "বার্গার"),
        "🍟" to listOf("fries", "ফ্রাই"),
        "🌯" to listOf("wrap", "roll", "রোল"),
        "🍰" to listOf("cake slice", "dessert", "কেক", "মিষ্টি"),
        "🧁" to listOf("cupcake", "কেক"),
        "🍬" to listOf("candy", "chocolate", "মিষ্টি", "লজেন্স"),
        "🍫" to listOf("chocolate", "চকলেট"),
        "🍨" to listOf("ice cream", "আইসক্রিম"),
        "🍦" to listOf("soft serve", "ice cream", "আইসক্রিম"),
        "🍧" to listOf("shaved ice", "borof", "আইসক্রিম"),
        "🥭" to listOf("mango", "aam", "আম"),
        "🍌" to listOf("banana", "kola", "কলা"),
        "🥥" to listOf("coconut", "narikel", "নারিকেল", "ডাব"),
        "🍉" to listOf("watermelon", "tormuj", "তরমুজ"),
        "🍎" to listOf("apple", "আপেল"),
        "🍊" to listOf("orange", "komla", "কমলা"),
        "🍋" to listOf("lemon", "lebu", "লেবু"),
        "🍇" to listOf("grapes", "angur", "আঙুর"),
        "🍍" to listOf("pineapple", "anarosh", "আনারস"),
        "🫖" to listOf("teapot", "cha", "চা"),
        "☕" to listOf("tea", "coffee", "cha", "চা", "কফি"),
        "🧋" to listOf("bubble tea", "চা"),
        "🥤" to listOf("drink", "cold drink", "কোক", "পানীয়"),
        "💧" to listOf("water drop", "pani", "পানি", "ফোঁটা"),
        "🍽️" to listOf("plate", "khabar", "খাবার", "প্লেট"),

        // ── Activities & objects ───────────────────────────────────────────
        "⚽" to listOf("football", "soccer", "futbol", "ফুটবল", "খেলা"),
        "🏏" to listOf("cricket", "bat", "ক্রিকেট", "খেলা"),
        "🏆" to listOf("trophy", "cup", "winner", "কাপ", "চ্যাম্পিয়ন", "জয়"),
        "🥇" to listOf("gold medal", "first", "প্রথম", "সোনা"),
        "🎮" to listOf("game", "gaming", "গেম", "খেলা"),
        "🎵" to listOf("music", "gaan", "গান", "সুর"),
        "🎶" to listOf("music notes", "gaan", "গান"),
        "🎤" to listOf("mic", "sing", "gaan", "গান", "মাইক"),
        "🎧" to listOf("headphone", "music", "গান", "হেডফোন"),
        "📱" to listOf("phone", "mobile", "মোবাইল", "ফোন"),
        "💻" to listOf("laptop", "computer", "ল্যাপটপ", "কম্পিউটার"),
        "📚" to listOf("books", "study", "boi", "বই", "পড়া"),
        "📖" to listOf("book", "read", "boi", "বই", "পড়া"),
        "✏️" to listOf("pencil", "write", "pencil", "পেনসিল", "লেখা"),
        "🖊️" to listOf("pen", "kolom", "কলম"),
        "📝" to listOf("memo", "note", "লেখা", "নোট"),
        "🎓" to listOf("graduation", "degree", "pass", "পাস", "গ্র্যাজুয়েশন"),
        "💼" to listOf("briefcase", "office", "job", "চাকরি", "অফিস"),
        "💰" to listOf("money bag", "taka", "টাকা", "ধন"),
        "💸" to listOf("money wings", "taka", "খরচ", "টাকা"),
        "💵" to listOf("dollar", "money", "taka", "টাকা"),
        "🕰️" to listOf("clock", "somoy", "সময়", "ঘড়ি"),
        "⏰" to listOf("alarm", "somoy", "সময়", "এলার্ম"),
        "📷" to listOf("camera", "photo", "ছবি", "ক্যামেরা"),
        "🎬" to listOf("movie", "film", "সিনেমা", "মুভি"),
        "🚗" to listOf("car", "gari", "গাড়ি"),
        "🚌" to listOf("bus", "বাস"),
        "🚲" to listOf("bicycle", "cycle", "সাইকেল"),
        "🛺" to listOf("auto rickshaw", "cng", "সিএনজি", "রিকশা", "অটো"),
        "🚂" to listOf("train", "rel", "ট্রেন", "রেল"),
        "✈️" to listOf("plane", "flight", "biman", "বিমান", "প্লেন"),
        "🚢" to listOf("ship", "launch", "jahaj", "জাহাজ", "লঞ্চ"),
        "🏠" to listOf("home", "house", "basa", "bari", "বাসা", "বাড়ি"),
        "🏥" to listOf("hospital", "hashpatal", "হাসপাতাল", "ডাক্তার"),
        "🏫" to listOf("school", "স্কুল"),
        "🛒" to listOf("cart", "bazar", "shopping", "বাজার", "কেনাকাটা"),
        "🎒" to listOf("bag", "school bag", "ব্যাগ"),
        "👗" to listOf("dress", "jama", "জামা", "পোশাক"),
        "👕" to listOf("shirt", "jama", "শার্ট", "জামা"),
        "👟" to listOf("shoe", "juta", "জুতা"),
        "💍" to listOf("ring", "engagement", "biye", "আংটি", "বিয়ে"),
        "🕶️" to listOf("sunglasses", "চশমা", "সানগ্লাস"),
        "☂️" to listOf("umbrella", "chata", "ছাতা", "বৃষ্টি"),
        "🔔" to listOf("bell", "notification", "ঘণ্টা", "বেল"),
        "💡" to listOf("bulb", "idea", "আইডিয়া", "বাতি"),
        "🔋" to listOf("battery", "charge", "চার্জ", "ব্যাটারি"),
        "📶" to listOf("signal", "network", "নেট", "সিগনাল"),
        "📞" to listOf("phone call", "call", "ফোন", "কল"),
        "💌" to listOf("love letter", "chithi", "চিঠি", "ভালোবাসা"),
        "📩" to listOf("mail", "message", "মেসেজ", "চিঠি"),
        "🎯" to listOf("target", "goal", "লক্ষ্য", "টার্গেট"),
        "🕐" to listOf("one oclock", "somoy", "সময়", "ঘড়ি"),

        // ── Flags ──────────────────────────────────────────────────────────
        "🇧🇩" to listOf("bangladesh", "bd flag", "বাংলাদেশ", "পতাকা", "দেশ"),
        "🇮🇳" to listOf("india", "ভারত", "পতাকা"),
        "🇵🇰" to listOf("pakistan", "পাকিস্তান", "পতাকা"),
        "🇸🇦" to listOf("saudi arabia", "সৌদি", "পতাকা"),
        "🇦🇪" to listOf("uae", "dubai", "দুবাই", "আমিরাত"),
        "🇺🇸" to listOf("usa", "america", "আমেরিকা", "পতাকা"),
        "🇬🇧" to listOf("uk", "britain", "london", "লন্ডন", "যুক্তরাজ্য"),
        "🇲🇾" to listOf("malaysia", "মালয়েশিয়া"),
        "🇸🇬" to listOf("singapore", "সিঙ্গাপুর"),
        "🇶🇦" to listOf("qatar", "কাতার"),
        "🇰🇼" to listOf("kuwait", "কুয়েত"),
        "🇴🇲" to listOf("oman", "ওমান"),
        "🇮🇹" to listOf("italy", "ইতালি"),
        "🇧🇷" to listOf("brazil", "ব্রাজিল"),
        "🇦🇷" to listOf("argentina", "আর্জেন্টিনা", "মেসি")
    )
}
